### ISSUE TITLE
phone number input should follow format

### ISSUE THREAD

**Issue by csell5** [HelloUnspecified/unspecified.io#36]
![image](https://user-images.githubusercontent.com/772569/79469537-ebd34d80-7fc5-11ea-8d83-1aaf3135a8ab.png)

but get 

![image](https://user-images.githubusercontent.com/772569/79469595-fdb4f080-7fc5-11ea-81f8-c9e3ce3a1c8b.png)

**Comment by saragibby** [comment]
closing this as a duplicate of #35
